### ISSUE TITLE
"pip install pydnp3" on windows10

### ISSUE THREAD

**Issue by pzg250** [ChargePoint/pydnp3#3]
when I use pip install pydnp3 to install pydnp3 package on windows10, there is an error that shows errors as below. Any suggestion? Thx

 pip install pydnp3
Collecting pydnp3
  Using cached https://files.pythonhosted.org/packages/3d/7b/9da4115503bdce211323caaa12ad7a5128470366a62cdc9c3877549d0be5/pydnp3-0.1.0.tar.gz
Requirement already satisfied: pybind11>=2.2 in c:\program files\python37\lib\site-packages (from pydnp3) (2.2.3)
Installing collected packages: pydnp3
  Running setup.py install for pydnp3 ... error
    Complete output from command "c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-phu88ytc\\pydnp3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-w5bs56zh\install-record.txt --single-version-externally-managed --compile:
    c:\program files\python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_ext
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:3 (project):
      Generator

        NMake Makefiles

      does not support platform specification, but platform

        x64

      was specified.

    CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Administrator/AppData/Local/Temp/pip-install-phu88ytc/pydnp3/build/temp.win-amd64-3.7/Release/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-phu88ytc\pydnp3\setup.py", line 89, in <module>
        zip_safe=False,
      File "c:\program files\python37\lib\site-packages\setuptools\__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python37\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python37\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python37\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python37\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python37\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python37\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python37\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-phu88ytc\pydnp3\setup.py", line 34, in run
        self.build_extension(ext)
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-phu88ytc\pydnp3\setup.py", line 59, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "c:\program files\python37\lib\subprocess.py", line 328, in check_call
        raise CalledProcessError(retcode, cmd)

**Comment by anhnguyen-cpi** [comment]
The "pip install pydnp3" is currently built for ubuntu 16.04 and MacOS. Can you try to follow the readme and build it from source to see if you have the same issue? 

I noticed that Garret made some change to enable building on Windows and with alternative versions of Python, you can check it out to see if it fixes the issue: https://github.com/smartergridsolutions/pydnp3

**Comment by pzg250** [comment]
@anhnguyen-cpi Thank u very much for your comments. It has the same error when I try to build the dnp3 from source. I will try Garrent's version.

**Comment by ujjavaljoshi** [comment]
Hi, Thanks for the new release for Windows. I have encountered below issue of heap size while compiling on Windows. 

     6>cl : Command line warning D9002: ignoring unknown option '-fvisibility=h
       idden' [C:\pydnp3\build\temp.win-amd64-3.5\Release\pydnp3.vcxproj]
         pydnp3.cpp
         Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For exampl
         e:
         - add -D_WIN32_WINNT=0x0501 to the compiler command line; or
         - add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
         Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
     6>c:\pydnp3\deps\dnp3\cpp\libs\include\openpal\util\comparisons.h(55): war
       ning C4146: unary minus operator applied to unsigned type, result still
       unsigned [C:\pydnp3\build\temp.win-amd64-3.5\Release\pydnp3.vcxproj]
         c:\pydnp3\src\openpal\util\comparisons.h(74): note: see reference to f
         unction template instantiation 'bool openpal::FloatEqual<T>(T,T,T)' be
         ing compiled
                 with
                 [
                     T=uint32_t
                 ]
         c:\pydnp3\src\openpal\util\comparisons.h(80): note: see reference to f
         unction template instantiation 'void declareComparisions<uint32_t>(pyb
         ind11::module &)' being compiled
         c:\pydnp3\deps\pybind11\include\pybind11\cast.h(1501): note: see refer
         ence to class template instantiation 'pybind11::detail::descr<8>' bein
         g compiled
         c:\pydnp3\deps\pybind11\include\pybind11\cast.h(1499): note: see refer
         ence to class template instantiation 'pybind11::detail::descr<5>' bein
         g compiled
         c:\pydnp3\deps\pybind11\include\pybind11\cast.h(1054): note: see refer
         ence to class template instantiation 'pybind11::detail::descr<7>' bein
         g compiled
     6>c:\pydnp3\deps\pybind11\include\pybind11\cast.h(1874): fatal error C1060
       : compiler is out of heap space [C:\pydnp3\build\temp.win-amd64-3.5\Rele
       ase\pydnp3.vcxproj]
     6>Done Building Project "C:\pydnp3\build\temp.win-amd64-3.5\Release\pydnp3
       .vcxproj" (default targets) -- FAILED.
     1>Done Building Project "C:\pydnp3\build\temp.win-amd64-3.5\Release\ALL_BU
       ILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

**Comment by bbarcklay-cpi** [comment]
The currently build seems to require at least 8Gb free memory.  We encounter a similar problem on Linux when running with less than 8Gb.  How much memory is available on your build machine?

**Comment by ujjavaljoshi** [comment]
@bbarcklay-cpi . The current machine has less than 6Gb memory. I will try with different machine and let you know the result. 

Thanks for the feedback.

**Comment by garretfick** [comment]
I have moved my changes for building on Windows to a different repo. The work breaks things into multiple compilation units so you need ~3 GB memory instead of much more

https://github.com/garretfick/pydnp3/

You want the branch feature/COMPILE_WINDOWS

**Comment by garretfick** [comment]
I have also created a pull request so hopefully this can make it into the main repo
https://github.com/ChargePoint/pydnp3/pull/13

**Comment by Kudrat9** [comment]
Hi, I'm trying to build pydnp3 on Windows and I used this repo:

https://github.com/garretfick/pydnp3/

However, I encounter several errors (same as building the previous repo).
[log.txt](https://github.com/ChargePoint/pydnp3/files/3306925/log.txt)

**Comment by anhnguyen-cpi** [comment]
@Kudrat9 Have you tried to build the pydnp3 from https://github.com/garretfick/pydnp3/tree/feature/COMPILE_WINDOWS using ~3GB memory as @garretfick mentioned?

**Comment by Kudrat9** [comment]
Yes, I did. But it generated the same errors. Also, I'm running it on my host machine. So, memory is not an issue. I'm running on Windows 10 and I tried Python 2.7 and 3.6.

**Comment by garretfick** [comment]
I'll take a look but might take a day as I'm travelling.

**Comment by garretfick** [comment]
I was able to build the project myself, without problems.

My steps were to open the project with Visual Studio 2019 and us it's cmake capabilities to build the project.

**Comment by Kudrat9** [comment]
I'm building it on VS 2017 now. But it got stuck after "Target info extraction done". Been stuck for a while now but doesn't show any errors.
![image](https://user-images.githubusercontent.com/51246738/59863101-ec18a300-9338-11e9-8037-0f810b4e2671.png)

**Comment by Kudrat9** [comment]
I am building the project on VS 2017. Did you get this output from CMake?
![image](https://user-images.githubusercontent.com/51246738/59864277-4adf1c00-933b-11e9-9d70-1d7992686199.png)

**Comment by Kudrat9** [comment]
I'm trying to build the project in VS 2017 now. I'm getting the error "Cannot open include file: asio.hpp: No such file or directory" even though I have defined ASIO_HOME as an environment variable.

**Comment by garretfick** [comment]
The asio.hpp error happens if you have not cloned the submodule in the dnp3
dependency.

**Comment by Kudrat9** [comment]
I was able to fix the asio error. But then I got the same errors as before. So, I installed VS 2019. When the cmake runs, it works fine.
![outt](https://user-images.githubusercontent.com/51246738/59875693-44aa6900-9356-11e9-92e7-c4d5f2c08781.png)

But when I do the build, it gives me errors.
![err](https://user-images.githubusercontent.com/51246738/59875709-51c75800-9356-11e9-89b0-2cf294f42536.png)

Most of them seem like syntax errors. Can you tell me which compiler did you use? I tried clang and msvc_x64. But I get the same result. Also, how much RAM is on your system? I just want to make sure it's not a memory issue since I faced that while installing pydnp3 on my linux VM.

**Comment by garretfick** [comment]
This is my cmake configure output:

```
1> CMake generation started.
1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\gfick\CMakeBuilds\6740193d-fe50-1334-9dc0-121c5c224dce\install\x64-Debug (default)" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\gfick\Dev\pydnp3"
1> Working directory: C:\Users\gfick\CMakeBuilds\6740193d-fe50-1334-9dc0-121c5c224dce\build\x64-Debug (default)
1> [CMake] -- The C compiler identification is MSVC 19.20.27508.1
1> [CMake] -- The CXX compiler identification is MSVC 19.20.27508.1
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.20.27508/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] CMake build is: Debug
1> [CMake] -- Found PythonInterp: C:/Users/gfick/AppData/Local/Programs/Python/Python37/python.exe (found version "3.7.3") 
1> [CMake] -- Found PythonLibs: C:/Users/gfick/AppData/Local/Programs/Python/Python37/libs/Python37.lib
1> [CMake] -- pybind11 v2.3.dev0
1> [CMake] CMake build is: Debug
1> [CMake] ASIO has been checked out as a git submodule: C:/Users/gfick/Dev/pydnp3/deps/dnp3/deps/asio/asio/include
1> [CMake] -- Performing Test HAS_MSVC_GL_LTCG
1> [CMake] -- Performing Test HAS_MSVC_GL_LTCG - Failed
1> [CMake] -- LTO disabled (not supported by the compiler and/or linker)
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/Users/gfick/CMakeBuilds/6740193d-fe50-1334-9dc0-121c5c224dce/build/x64-Debug (default)
1> [CMake] 
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Tests found, but none that match the current build type of Debug.
1> Target info extraction done.
1> CMake generation finished.
```

Look like your compiler version is newer and I think you are using msvc_x64

**Comment by Kudrat9** [comment]
I actually looked into it but found this:

https://groups.google.com/forum/#!topic/automatak-dnp3/hZxt_6hirhY

It's just a warning, and the ASIO_HOME tells where asio is located. So, I don't suppose that is an issue.

**Comment by garretfick** [comment]
I'm not convinced either way with regard to ASIO.

Are you able to show the first error from Visual Studio or the complete compile output. I see the screen shot has 11 errors, but there are only 10 in the screen shot you provided.

**Comment by garretfick** [comment]
On a separate thread - how did you get ASIO? What version are you using?

**Comment by Kudrat9** [comment]
The 11th error was a memory issue. But later, I compiled on a bigger system and it was gone. And these 10 errors remained. 

I downloaded ASIO from here (and added to the deps folder in dnp3):
https://think-async.com/Asio/Download.html

**Comment by garretfick** [comment]
Gut feeling I have is that you are using a different version of ASIO.

The version I have for ASIO has the following in `serial_port.hpp`:

```
namespace asio {

/// Typedef for the typical usage of a serial port.
typedef basic_serial_port<> serial_port;

} // namespace asio
```

Downloading the latest from the site you linked, I see the following:

```
namespace asio {

#if defined(ASIO_ENABLE_OLD_SERVICES)
// Typedef for the typical usage of a serial port.
typedef basic_serial_port<> serial_port;
#else // defined(ASIO_ENABLE_OLD_SERVICES)
...

```

So, if `ASIO_ENABLE_OLD_SERVICES` is not defined, then I think you would get error C2039 from your screen shot.

**Comment by Kudrat9** [comment]
Oh ok, I'll try using the other version (1.10.8) and see if that works.

**Comment by garretfick** [comment]
Finally found the version number I have - I think it is 1.10.8. Try downloading that version of ASIO then try again.

**Comment by garretfick** [comment]
You also asked about my system - my system has 16 GB, but part of that is normally reserved for Hyper-V, so usually at most 14 GB.

**Comment by garretfick** [comment]
@Kudrat9 did that solve the problem for you?

**Comment by Kudrat9** [comment]
I got rid of the ASIO warning after replacing the library with the older version. But I get this error when I build pydnp3.
![build](https://user-images.githubusercontent.com/51246738/60032846-4167f380-965c-11e9-8397-3183db661abd.png)

I ran the build a couple times. Whenever I clean the previous build, I see the number of files being cleaned is different. Which is giving me the feeling its still having some memory issue (despite the fact that I ran it on 16 GB system). Any ideas?

**Comment by Kudrat9** [comment]
This is the error output, which shows same errors as before.
![error](https://user-images.githubusercontent.com/51246738/60033020-9d327c80-965c-11e9-8b23-93c516db8431.png)

**Comment by garretfick** [comment]
**The bad news**

This looks like an issue with opendnp3 (not pydnp3). It has been fixed in opendp3, but I've been unable to find a way automatically solve it here.


**The good news**
You can "easily" fix this by adding `#include <string>` to `deps\dnp3\cpp\libs\include\asiodnp3\IMasterOperations.h`

I need to investigate a bit more about why this isn't happening for Linux and whether I can just update the opendnp3 version, but I hope that should un-block you for now.

**Comment by garretfick** [comment]
@Kudrat9 I also pushed an update that eliminates the warning about `visibility=hidden`

**Comment by garretfick** [comment]
I have pushed another update that somewhat solves this automatically.

I have fixed `setup.py` so that it works. It detects if `IMasterOperations.h` needs a patch, and if so, applies the patch. You can run `python setup.py install` and the build should succeed.

Note that if you run via cmake directly (or Visual Studio), then the patch is not automatically applied and you need to do it manually as described above.

Hopefully this works :)

**Comment by Kudrat9** [comment]
@garretfick Thanks! This worked. I was able to build it both using VS 2019 and python setup.py install.

I will install the new update to get rid of the warnings.
Thanks for the help! :)

**Comment by garretfick** [comment]
Great. Hopefully @anhnguyen-cpi 's testing passes and then this can be merged and then fix the underlying issue by updating to a newer version of OpenDNP3.

**Comment by benhuynh-eaton** [comment]
hi I am currently trying to install the pydnp3 library. My setup configurations are Python 3.8, Visual Studio 2019 and Cmake 3.2.7. I am currently getting this error 
![MicrosoftTeams-image](https://github.com/ChargePoint/pydnp3/assets/136386147/cac201ec-6294-4b4c-b0f6-67ee0a827cf7)
\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\E0757436\\Desktop\\dnp3\\pydnp3', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\E0757436\\Desktop\\dnp3\\pydnp3\\build\\lib.win32-cpython-38', '-DPYTHON_EXECUTABLE=C:\\Users\\E0757436\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\E0757436\\Desktop\\dnp3\\pydnp3\\build\\lib.win32-cpython-38']' returned non-zero exit status 1.

I was wondering if anyone had a fix for this?

**Comment by benhuynh-eaton** [comment]
Should say that I have tried upgrading setup tool, and I am running Windows 10

**Comment by vidyaspatil-eaton** [comment]
> [@garretfick](https://github.com/garretfick) Thanks! This worked. I was able to build it both using VS 2019 and python setup.py install.
> 
> I will install the new update to get rid of the warnings. Thanks for the help! :)



> [@garretfick](https://github.com/garretfick) Thanks! This worked. I was able to build it both using VS 2019 and python setup.py install.
> 
> I will install the new update to get rid of the warnings. Thanks for the help! :)

Hi, 
Can you please mention the exact steps, how it worked? as i am also getting below error in Developer Power shell:


PS C:\Garretficklink\pydnp3> python setup.py install
C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running install
C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating pyopendnp3.egg-info
writing pyopendnp3.egg-info\PKG-INFO
writing dependency_links to pyopendnp3.egg-info\dependency_links.txt
writing requirements to pyopendnp3.egg-info\requires.txt
writing top-level names to pyopendnp3.egg-info\top_level.txt
writing manifest file 'pyopendnp3.egg-info\SOURCES.txt'
reading manifest file 'pyopendnp3.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'pyopendnp3.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
setup.py:33: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  cmake_version = LooseVersion(re.search(r'version\s*([\d.]+)', out.decode()).group(1))
-- Building for: NMake Makefiles
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.10 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.


CMake Error at CMakeLists.txt:3 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    setup(
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
    return run_commands(dist)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
    dist.run_commands()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 999, in run_command
    super().run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 96, in run
    self.do_egg_install()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install.py", line 148, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 999, in run_command
    super().run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 177, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in call_command
    self.run_command(cmdname)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 999, in run_command
    super().run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\command\install_lib.py", line 19, in run
    self.build()
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 999, in run_command
    super().run_command(command)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.build_extension(ext)
  File "setup.py", line 63, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "C:\Users\Validation\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'C:\\Garretficklink\\pydnp3', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Garretficklink\\pydnp3\\build\\lib.win-amd64-cpython-38', '-DPYTHON_EXECUTABLE=C:\\Users\\Validation\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Garretficklink\\pydnp3\\build\\lib.win-amd64-cpython-38', '-A', 'x64']' returned non-zero exit status 1.
PS C:\Garretficklink\pydnp3>
